# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Build docker make and Cleanup

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/defconfig_rm.yml'
env:
   REPO_NUTTX_NAME: apache/nuttx
   REF_NUTTX_NAME: master
   REPO_APPS_NAME: apache/nuttx-apps
   REF_APPS_NAME: master
   BOARD_CONFIG_NAME: esp32s2-saola-1:mcuboot_update_agent

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Fetch-Source:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Target Branches
        id: gittargets
        shell: bash
        run: |
          OS_REF=""
          APPS_REF=""
          REF="refs/heads/master"
          echo "Working with ref: $REF"
      - name: Checkout nuttx repo
        uses: actions/checkout@v6
        with:
          repository: ${{ env.REPO_NUTTX_NAME }}
          ref: ${{ env.REF_NUTTX_NAME }}
          path: sources/nuttx
          fetch-depth: 1
      - name: Checkout nuttx repo tags
        run: git -C sources/nuttx fetch --tags

      - name: Checkout apps repo
        uses: actions/checkout@v6
        with:
          repository: ${{ env.REPO_APPS_NAME }}
          ref: ${{ env.REF_APPS_NAME }}
          path: sources/apps
          fetch-depth: 1

      - name: Tar sources
        run: tar zcf sources.tar.gz sources

      - name: Archive Source Bundle
        uses: actions/upload-artifact@v5
        with:
          name: source-bundle
          path: sources.tar.gz
  LinuxMake:
    needs: Fetch-Source
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      GH_JOB_NAME: ${{ github.job }}

    steps:
      - name: Show disk usage
        run: df -h

      - name: Top-level directories
        run: du -h -d1 / | sort -hr | head -n 20

      - name: Detailed file sizes
        run: find / -type f -exec du -h {} + 2>/dev/null | sort -hr | head -n 1000

      - name: Download Source Artifact
        uses: actions/download-artifact@v6
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: tar zxf sources.tar.gz

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        run: docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux

      - name: Export NuttX Repo SHA
        run: echo "nuttx_sha=`git -C sources/nuttx rev-parse HEAD`" >> $GITHUB_ENV

      - name: Run builds
        uses: ./sources/nuttx/.github/actions/ci-container
        env:
          BLOBDIR: /tools/blobs
        with:
          run: |
            echo "Job: ${{ env.GH_JOB_NAME }}"
            echo "::add-matcher::sources/nuttx/.github/gcc.json"
            export ARTIFACTDIR=`pwd`/buildartifacts
            echo "ARTIFACTDIR: $ARTIFACTDIR"
            git config --global --add safe.directory /github/workspace/sources/nuttx
            git config --global --add safe.directory /github/workspace/sources/apps
            cd sources/nuttx
            ./tools/configure.sh -l ${{ env.BOARD_CONFIG_NAME }}
            make -j
            # make V=1
            df -h
            artifactconfigdir=$ARTIFACTDIR/$(echo ${{ env.BOARD_CONFIG_NAME }} | sed "s/:/\//")/
            echo "artifactconfigdir: $artifactconfigdir"
            mkdir -p $artifactconfigdir
            xargs -I "{}" cp "{}" $artifactconfigdir < nuttx.manifest

      - uses: actions/upload-artifact@v5
        if: ${{ always() }}
        with:
          name: linux-${{ github.job }}-builds
          path: buildartifacts/
        continue-on-error: true

  LinuxCleanup:
    needs: Fetch-Source
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      GH_JOB_NAME: ${{ github.job }}

    steps:
      - name: Show disk usage
        run: df -h

      - name: Top-level directories
        run: du -h -d1 / | sort -hr | head -n 20

      - name: Detailed file sizes
        run: find / -type f -exec du -h {} + 2>/dev/null | sort -hr | head -n 1000

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Free Disk Space (Ubuntu)
        uses: ./.github/actions/free-disk-space
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false
      # - name: Cleanup
      #  uses: actions/checkout@v6
      #  run: |
        # Remove mysql
      #  sudo apt-get remove -y '^mysql-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mysql-.*' --fix-missing] failed to complete successfully. Proceeding..."

      - name: Download Source Artifact
        uses: actions/download-artifact@v6
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: tar zxf sources.tar.gz

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        run: docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux

      - name: Export NuttX Repo SHA
        run: echo "nuttx_sha=`git -C sources/nuttx rev-parse HEAD`" >> $GITHUB_ENV

      - name: Run builds
        uses: ./sources/nuttx/.github/actions/ci-container
        env:
          BLOBDIR: /tools/blobs
        with:
          run: |
            echo "Job: ${{ env.GH_JOB_NAME }}"
            echo "::add-matcher::sources/nuttx/.github/gcc.json"
            export ARTIFACTDIR=`pwd`/buildartifacts
            echo "ARTIFACTDIR: $ARTIFACTDIR"
            git config --global --add safe.directory /github/workspace/sources/nuttx
            git config --global --add safe.directory /github/workspace/sources/apps
            cd sources/nuttx
            ./tools/configure.sh -l ${{ env.BOARD_CONFIG_NAME }}
            make -j
            df -h
            # make V=1
            artifactconfigdir=$ARTIFACTDIR/$(echo ${{ env.BOARD_CONFIG_NAME }} | sed "s/:/\//")/
            echo "artifactconfigdir: $artifactconfigdir"
            mkdir -p $artifactconfigdir
            xargs -I "{}" cp "{}" $artifactconfigdir < nuttx.manifest

      - uses: actions/upload-artifact@v5
        if: ${{ always() }}
        with:
          name: linux-${{ github.job }}-builds
          path: buildartifacts/
        continue-on-error: true
